version: '3'

services:
    postgres-container:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=rootroot123
        ports:
            - 5432:5432
        volumes:
            - database-data:/var/lib/postgres/data

volumes:
    database-data: {}
