version: '3'

services:
    db:
        container_name: postgres-container
        image: postgres:14-alpine3.15
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres123
            POSTGRES_DB: typeorm
        ports:
            - 5432:5432
        volumes:
            - ./pg-data:/var/lib/postgres/data

    api:
        container_name: api-container
        build: .
        image: api:dev
        restart: always
        ports:
            - 8080:8080
        expose:
            - 8080
        volumes:
            - ./:/usr/src/api
